n2/urls.py
from django.conf.urls import patterns, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from n2 import views
from n2project import settings

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^login$', views.vlogin, name='login'),
    url(r'^logout$', views.vlogout, name='logout'),
    url(r'^register$', views.vregister, name='register'),
    url(r'^activate/(?P<user_pk>\d+)/(?P<activation_key>\w+)', views.activate_user, name='activate'),
    url(r'^notice/(?P<notice_id>\d+)$', views.notice, name='notice'),
    url(r'^compose$', views.compose, name='compose_new'),
    url(r'^compose/(?P<notice_id>\d+)$', views.compose, name='compose_edit'),
    url(r'^profile$', views.edit_user, name='edit_user'),
    url(r'^reset$', views.reset_password, name='reset'),
    url(r'^about$', views.about, name='about'),
    url(r'^register_complete$', views.register_complete, name='register_complete'),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

urlpatterns += staticfiles_urlpatterns()

n2project/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

# Moderator and Admin
from n2.moderator_site import moderator_site

# Dajaxice (1/2)
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
dajaxice_autodiscover()
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('',
    url(r'^admin/', include(moderator_site.urls)),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
    url(r'', include('n2.urls', namespace='n2')),
)

# Dajaxice (2/2)
urlpatterns += staticfiles_urlpatterns()

handler403 = 'n2.views.page403'
handler404 = 'n2.views.page404'
handler500 = 'n2.views.page500'

n2/models.py
import uuid
from django.db import models
from django.contrib.auth.models import UserManager, AbstractUser
from django.utils import timezone
from n2project import settings
import os

STATUS = (
    ('a', 'Approved'),
    ('d', 'Disapproved'),
    ('p', 'Pending'),
)

class TagGroup(models.Model):
    tagGroupName = models.CharField(max_length=100)
    
    tagGroupName.short_description = 'Tag Group Name'

    def __unicode__(self):
        return self.tagGroupName

class Tag(models.Model):
    tagGroup = models.ForeignKey(TagGroup)
    tagName = models.CharField(max_length=100)
    status = models.CharField(max_length=1, choices=STATUS)
    
    tagName.short_description = 'Tag Name'
    
    class Meta:
        permissions = (
            ('approve_tag', 'Approve new tags'),
        )

    def __unicode__(self):
        return self.tagName

class Notice(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length=200)
    content = models.CharField(max_length=5000)
    dateCreated = models.DateTimeField()
    datePublished = models.DateTimeField()
    dateExpired = models.DateTimeField()
    status = models.CharField(max_length=1, choices=STATUS)
    viewCount = models.IntegerField()
    tags = models.ManyToManyField(Tag, blank=True)
    originalNotice = models.OneToOneField('Notice', blank=True, null=True, on_delete=models.SET_NULL)
    image = models.ImageField(upload_to="notices/"+str(uuid.uuid4()), blank=True, null=True)

    class Meta:
        permissions = (
            ('approve_notice', 'Approve new notice or modification to existing one'),
            ('directly_post_notice', 'Directly post new notice without being reviewed'),
        )

    def __unicode__(self):
        return self.title

    def num_views(self):
        return len(self.viewedBy.all())

    def num_likes(self):
        return len(self.likedBy.all())
    
    def is_published(self):
        return self.datePublished.toordinal() - timezone.now().toordinal() <= 0 and self.status == 'a'
    
    def is_expired(self):
        return self.dateExpired.toordinal() - timezone.now().toordinal() < 0

    def delete(self, *args, **kwargs):
        storage, path = self.image.storage, self.image.path
        super(Notice, self).delete(*args, **kwargs)
        storage.delete(path)

class N2User(AbstractUser):
    status = models.CharField(max_length=1, choices=STATUS)
    preferredTags = models.ManyToManyField(Tag, blank=True, null=True)
    bookmarkedNotices = models.ManyToManyField(Notice, blank=True, null=True, related_name="bookmarkedBy")
    likedNotices = models.ManyToManyField(Notice, blank=True, null=True, related_name="likedBy")
    viewedNotices = models.ManyToManyField(Notice, blank=True, null=True, related_name="viewedBy")
    hiddenNotices = models.ManyToManyField(Notice, blank=True, null=True, related_name="hiddenBy")
    activationKey = models.CharField(max_length=50, blank=True, null=True)
    objects = UserManager()
    
    class Meta:
        permissions = (
            ('block_user', 'Block or unblock user'),
            ('grant_direct_post', 'Grant or un-grant a direct post permission'),
            ('reset_password', 'Reset other user\'s password'),
            ('change_user_group', 'Change user from/to moderator group, etc.'),
        )

    def __unicode__(self):
        return str(self.username)
    
    def can_post_notice_directly(self):
        return self.has_perm('n2.directly_post_notice')
    can_post_notice_directly.boolean = True
    can_post_notice_directly.short_description = 'Can post notice directly?'

n2/forms.py
from datetime import datetime
from django import forms
from n2.models import Tag, TagGroup
from django.forms import extras
from n2project import settings

error_messages = {'required': 'Required',
                  'max_length': 'Too long',
                  'min_length': 'Too short',
                  'invalid': 'Invalid',
                  'invalid_choice': 'Invalid choice',
                  'invalid_list': 'Invalid list',
                  'missing': 'File is missing',
                  'empty': 'File is empty',
                  'invalid_image': 'Invalid image',
                  'max_value': 'Too big',
                  'min_value': 'Too small',
}

boolean_field_err_msg = {'required': 'Required',}

class login_form(forms.Form):
    username = forms.CharField(label="username", error_messages=error_messages)
    password = forms.CharField(widget=forms.PasswordInput, label="password", error_messages=error_messages)
    next = forms.CharField(widget=forms.HiddenInput, label="", error_messages=error_messages, required=False)

class register_form(forms.Form):
    username = forms.CharField(label="username", error_messages=error_messages)
    password = forms.CharField(widget=forms.PasswordInput, label="password", error_messages=error_messages)
    first_name = forms.CharField(label="first name", error_messages=error_messages)
    last_name = forms.CharField(label="last name", error_messages=error_messages)
    email = forms.EmailField(label="email", error_messages=error_messages)

def get_tags():
    all_tags = Tag.objects.filter(status='a')
    tag_choices = []
    for tag in all_tags:
        tag_choices.append((tag.pk, str(tag.tagGroup) + " - " + str(tag.tagName)))
    return tuple(tag_choices)

def get_all_tags():
    all_tags = []
    tag_groups = TagGroup.objects.all()
    for tag_group in tag_groups:
        tags = []
        for tag in tag_group.tag_set.filter(status='a'):
            tags.append({'pk': tag.pk, 'name': tag.tagName})
        all_tags.append({'group_name': tag_group.tagGroupName, 'tags': tags})
    return all_tags

class compose_form(forms.Form):
    title = forms.CharField(label="title", error_messages=error_messages)
    content = forms.CharField(label="content", widget=forms.Textarea, error_messages=error_messages)
    date_published = forms.DateField(label="date published", widget=extras.SelectDateWidget(), error_messages=error_messages)
    date_expired = forms.DateField(label="date expired", widget=extras.SelectDateWidget(), error_messages=error_messages)
    tags = forms.MultipleChoiceField(label="tags", widget=forms.CheckboxSelectMultiple, choices=get_tags(), required=False, error_messages=error_messages)
    image = forms.ImageField(label="image", required=False, error_messages=error_messages)
    original = forms.IntegerField(label="original", widget=forms.HiddenInput, initial=settings.NULL_PK, error_messages=error_messages)

def get_tag_groups():
    return [(tag_group.pk,tag_group.tagGroupName) for tag_group in TagGroup.objects.all()]
    
class add_tag_form(forms.Form):
    tag_name = forms.CharField(label='tag name', required=False, error_messages=error_messages)
    tag_group = forms.ChoiceField(label='tag group', choices=get_tag_groups(), required=False, error_messages=error_messages)
    
    def __init__(self, *args, **kwargs):
        super(add_tag_form, self).__init__(*args, **kwargs)
        self.fields['tag_name'].widget = forms.TextInput(attrs={'class':'tag_name_box'})
        self.fields['tag_group'].widget = forms.Select(attrs={'class':'tag_group_choice'})
        self.fields['tag_group'].choices = get_tag_groups()
        self.label_suffix = ''
    
    def as_table(self):
        from lxml import etree
        
        default = super(add_tag_form, self).as_table()
        added_root = '<root>'+default+'</root>'
        root = etree.fromstring(added_root)
        
        # Finds all input textfield tags
        inputs = []
        labels = []
        for i in root.iterdescendants():
            if i.tag == 'input' and 'type' in i.attrib and i.attrib['type'] == 'text':
                inputs.append(i)
            elif i.tag == 'label' and 'for' in i.attrib:
                labels.append(i)
        
        # Surround the found textfield input tags with the span tag
        for i in inputs:
            span = etree.Element('span')
            span.attrib['class'] = 'span_input_text span_input_text_create_tag'
            parent = i.getparent()
            parent.remove(i)
            parent.insert(0,span)
            span.insert(0,i)
        for l in labels:
            l.getparent().attrib['class'] = 'td_create_tag_label'
        
        # Return the modified tree back as string
        modified = ""
        for i in root:
            modified += etree.tostring(i, pretty_print=False)
        
        return modified

from django.forms.formsets import formset_factory
add_tag_formset = formset_factory(add_tag_form, extra=1)

class notice_search_form(forms.Form):
    keywords = forms.CharField(label="keywords", required=False, error_messages=error_messages)
    tags = forms.MultipleChoiceField(label="tags", widget=forms.CheckboxSelectMultiple, choices=get_tags(), required=False, error_messages=error_messages)
    show_hidden = forms.BooleanField(label="show_hidden", required=False, error_messages=error_messages)
    show_expired = forms.BooleanField(label="show_expired", required=False, error_messages=error_messages)
    bookmarked_only = forms.BooleanField(label="bookmarked_only", required=False, error_messages=error_messages)
    sort_choices = ( ('date_published', 'Recently published'),
                     ('num_views', 'Highest views'),
                     ('num_likes', 'Most liked'),
                   )
    sort_choice_default = 'date_published'
    sort_by = forms.ChoiceField(label="sort_by", widget=forms.RadioSelect, choices=sort_choices, initial=sort_choice_default, required=False, error_messages=error_messages)

    def __init__(self, *args, **kwargs):
        super(notice_search_form, self).__init__(*args, **kwargs)
        self.fields['tags'].choices = get_tags()
    
    
class user_form(forms.Form):
    username = forms.CharField(label="username", error_messages=error_messages)
    password = forms.CharField(widget=forms.PasswordInput, label="password", required=False, error_messages=error_messages)
    first_name = forms.CharField(label="first name", error_messages=error_messages)
    last_name = forms.CharField(label="last name", error_messages=error_messages)
    email = forms.EmailField(label="email", error_messages=error_messages)
    tags = forms.MultipleChoiceField(label="tags", widget=forms.CheckboxSelectMultiple, choices=get_tags(), required=False, error_messages=error_messages)

class file_form(forms.Form):
    uploaded = forms.ImageField(label='uploaded', error_messages=error_messages)

class admin_notice_form(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):
        super(admin_notice_form, self).__init__(*args, **kwargs)
        self.fields['content'].widget = forms.Textarea(attrs={'class':'vTextarea', 'cols':'50'})

class reset_password_form(forms.Form):
    username = forms.CharField(label="username", error_messages=error_messages)
    email = forms.EmailField(label="email", error_messages=error_messages)

templates/DELETE/base.html
<a href="{% url 'n2:index' %}"><h2>N2</h2></a>
<h3>{% block page_name %}{% endblock %}</h3>

{% if messages %}
    {% for message in messages %}
        <b><i>[{{ message.tags }}] {{ message|striptags }}</i></b><br/>
    {% endfor %}
{% endif %}

{% if stuff %}
    (Stuff: {{ stuff }})
{% endif %}

{% block content %}
    Hello. -N2
{% endblock %}

templates/DELETE/compose.html
{% extends "base.html" %}

{% block page_name %}{% spaceless %}
{{ editor_title }}
{% endspaceless %}{% endblock %}

{% block content %}

{% if error_msg %}
    [{{ error_msg }}]
{% endif %}
{% if form_errors %}
    {{ form_errors }}
{% endif %}

<form action="{% url 'n2:compose_new' %}" method="post" enctype="multipart/form-data">

    {% csrf_token %}

    <table>
        <tr>
            <td>
                <label for="id_title">title</label>
            </td>
            <td>
                {{ compose_form.title }}
            </td>
        </tr>

        <tr>
            <td rowspan>
                <label for="id_content">content</label>
            </td>
            <td>
                {{ compose_form.content }}
            </td>
        </tr>

        <tr>
            <td>
                <label for="id_date_published_month">publishing date</label>
            </td>
            <td>
                {{ compose_form.date_published }}
            </td>
        </tr>

        <tr>
            <td>
                <label for="id_date_expired_month">expiring date</label>
            </td>
            <td>
                {{ compose_form.date_expired }}
            </td>
        </tr>

        <tr>
            <td>
                <label for="id_image">image</label>
            </td>
            <td>
                {{ compose_form.image }}
            </td>
        </tr>

    </table>

    <h3>Tags</h3>

    {% for tag_group in all_tags %}
        <b>{{ tag_group.group_name }}</b><br/>
        {% for tag in tag_group.tags %}
            <label for="id_tags_{{ tag.pk }}"><input id="id_tags_{{ tag.pk }}" name="tags" type="checkbox" value="{{ tag.pk }}" {% if tag.pk in selected_tags %}checked="checked"{% endif %}/>{{ tag.name }}</label><br/>
        {% endfor %}
        <br/>
    {% endfor %}

{# David added formset #}
	<h4>Django powered formset</h4>
	<table id="new_tag_formsets">
	    {{ add_tag_formset }}
	</table>
	<a id="add_new_tag_formset" href="javascript:add_new_tag_formset()">Add more tag</a>
	<script type="text/javascript">
	var form_count = {{add_tag_formset.total_form_count}};
	function add_new_tag_formset()
	{
		var formString = '{{add_tag_formset.empty_form|escapejs}}'.replace(/__prefix__/g, form_count);
		var formset = document.getElementById('new_tag_formsets').getElementsByTagName('tbody')[0];
		appendHTMLStringToElement(formString, formset);
		form_count++;
		document.getElementById('id_form-TOTAL_FORMS').value = form_count;
	}//http://stackoverflow.com/questions/2353710/how-would-you-make-a-dynamic-formset-in-django
	
	/* Appends the given HTML string after the HTML element's innerHTML.
	 * This is more robust and general than simply doing:
	 *     element.innerHTML += HTMLString
	 * @param HTMLString The HTML string to append
	 * @param element The element to append the HTML string to
	 */
	function appendHTMLStringToElement(HTMLString, element)
	{
		var temporaryElement = document.createElement(element.tagName);
		temporaryElement.innerHTML = HTMLString;
		element.appendChild(temporaryElement);
		while (temporaryElement.childNodes.length > 0) {
			element.appendChild(temporaryElement.childNodes[0]);
		}
		element.removeChild(temporaryElement);
	}
    </script>
{# David added formset #}

    {{ compose_form.original }}

    <input type="submit" value="Submit"/>

</form>

{% if perms.n2 %}
Has some permission on n2 app
{% else %}
Does NOT have permission at all on n2 app
{% endif %}
<br />
{% if perms.n2.add_notice %}
Has permission to create notice
{% else %}
Does NOT have permission to create notice
{% endif %}

{% endblock %}

templates/DELETE/edit_user.html
{% extends "base.html" %}

{% block page_name %}{% spaceless %}
Edit your profile
{% endspaceless %}{% endblock %}

{% block content %}

{% if error_msg %}
    [{{ error_msg }}]
{% endif %}
{% if form_errors %}
    {{ form_errors }}
{% endif %}
<form action="{% url 'n2:edit_user' %}" method="post">

    {% csrf_token %}
    <table>
{#    {% for field in user_form %}#}
{#        <tr>#}
{#            <td>#}
{#                {{ field.label_tag }}#}
{#            </td>#}
{#            <td>#}
{#                {{ field }}#}
{#            </td>#}
{#            <td>#}
{#                {% if field.errors %}#}
{#                    {{ field.errors|striptags }}#}
{#                {% endif %}#}
{#            </td>#}
{#        </tr>#}
{#    {% endfor %}#}
	
		<tr>
            <td>
                <label for="id_username">username</label>
            </td>
            <td>
                {{ user_form.username }}
            </td>
            <td>
                {% if user_form.username.errors %}
                    {{ user_form.username.errors|striptags }}
                {% endif %}
            </td>
        </tr>
		<tr>
            <td>
                <label for="id_password">password</label>
            </td>
            <td>
                {{ user_form.password }}
            </td>
            <td>
                {% if user_form.password.errors %}
                    {{ user_form.password.errors|striptags }}
                {% endif %}
            </td>
        </tr>
		<tr>
            <td>
                <label for="id_first_name">first_name</label>
            </td>
            <td>
                {{ user_form.first_name }}
            </td>
            <td>
                {% if user_form.first_name.errors %}
                    {{ user_form.first_name.errors|striptags }}
                {% endif %}
            </td>
        </tr>
		<tr>
            <td>
                <label for="id_last_name">last_name</label>
            </td>
            <td>
                {{ user_form.last_name }}
            </td>
            <td>
                {% if user_form.last_name.errors %}
                    {{ user_form.last_name.errors|striptags }}
                {% endif %}
            </td>
        </tr>
		<tr>
            <td>
                <label for="id_email">email</label>
            </td>
            <td>
                {{ user_form.email }}
            </td>
            <td>
                {% if user_form.email.errors %}
                    {{ user_form.email.errors|striptags }}
                {% endif %}
            </td>
        </tr>
    </table>

    <h3>Preferred Tags</h3>
	{% if user_form.tags.errors %}
		{{ user_form.tags.errors|striptags }}
	{% endif %}
    {% for tag_group in all_tags %}
        <b>{{ tag_group.group_name }}</b><br />
        {% for tag in tag_group.tags %}
            <label for="id_tags_{{ tag.pk }}"><input id="id_tags_{{ tag.pk }}" name="tags" type="checkbox" value="{{ tag.pk }}" {% if tag.pk in preferred_tags %}checked="checked"{% endif %}/>{{ tag.name }}</label><br/>
        {% endfor %}
        <br />
    {% endfor %}
	
    <input type="submit" value="Save"/>

</form>
{% endblock %}

templates/DELETE/index.html
{% extends "base.html" %}

{% block page_name %}{% spaceless %}
Welcome
{% endspaceless %}{% endblock %}

{% block content %}

    Logged in as {{ user }}.
    <a href="{% url 'n2:edit_user' %}">Edit Profile</a>
    <a href="{% url 'n2:logout' %}">Log out.</a>
    <a href="{% url 'n2:compose_new' %}">Create notice.</a>

    <h3>Notices</h3>
    <ul>
        {% for notice in notices %}
             <li>
                 <a href="{% url 'n2:notice' notice.pk %}">{{ notice.title }}</a>
                 (by {{ notice.author }} on {{ notice.datePublished|date:"j M Y" }}) - {{ notice.num_views }} views, {{ notice.num_likes }} likes
             </li>
        {% endfor %}
    </ul>

    <form action="{% url 'n2:index' %}" method="get">

{#        {% csrf_token %}#}

        <table>
{#        {{ notice_search_form.as_table }}#}
{% comment %}
            <tr>
                <th><label for="id_keywords">keywords (optional)</label></th>
                <td>{{ notice_search_form.keywords }}</td>
                <td><input type="submit" value="Submit"/></td>
            </tr>
            <tr>
                <th><label for="id_show_hidden">show hidden</label></th>
                <td>{{ notice_search_form.show_hidden }}</td>
                <td></td>
            </tr>
            <tr>
                <th><label for="id_show_expired">show expired</label></th>
                <td>{{ notice_search_form.show_expired }}</td>
                <td></td>
            </tr>
            <tr>
                <th><label for="id_bookmarked_only">show bookmarked only</label></th>
                <td>{{ notice_search_form.bookmarked_only }}</td>
                <td></td>
            </tr>
            <tr>
                <th><label for="id_sort_by_0">sort by</label></th>
                <td>
                    <ul>
                        {{ notice_search_form.sort_by }}
                    </ul>
                </td>
                <td></td>
            </tr>
            <tr rowspan="3">
                <th><label for="id_tags_0">tags</label></th>
            </tr>
            <tr rowspan="3">
                <td>
                    {% for tag_group in all_tags %}
                        <b>{{ tag_group.group_name }}</b><br/>
                        {% for tag in tag_group.tags %}
                            <label for="id_tags_{{ tag.pk }}"><input id="id_tags_{{ tag.pk }}" name="tags" type="checkbox" value="{{ tag.pk }}" {% if tag.pk in selected_tags %}checked="checked"{% endif %}/>{{ tag.name }}</label><br/>
                        {% endfor %}
                        <br/>
                    {% endfor %}
                </td>
            </tr>
{% endcomment %}<input type="submit" value="Submit"/>
{{ notice_search_form }}
        </table>

{#        <h3>Tags</h3>#}
{#        {% for tagGroup in tagGroups %}#}
{#            Tags<br/>#}
{#                &nbsp;&nbsp;{{ tagGroup.tagGroupName }}<br/>#}
{#            {% for tag in tagGroup.tag_set.all %}#}
{#                &nbsp;&nbsp;&nbsp;&nbsp;<label><input type="checkbox" name="tags" value="{{ tag.pk }}"/>{{ tag.tagName }}</label><br/>#}
{#            {% endfor %}#}
{#        {% endfor %}#}

        <br/>

    </form>

    <h3>All Registered Users</h3>
    <ul>
    {% for rUser in allUsers %}
        <li>{{ rUser }} ({{ rUser.first_name }} {{ rUser.last_name }}, Status: {{ rUser.status }})</li>
    {% endfor %}
    </ul>

{% endblock %}

templates/DELETE/login.html
{% extends "base.html" %}

{% block page_name %}{% spaceless %}
Login
{% endspaceless %}{% endblock %}

{% block content %}

{% if error_msg %}
    [{{ error_msg }}]
{% endif %}
{% if form_errors %}
    {{ form_errors }}
{% endif %}

<form action="{% url 'n2:login' %}" method="post">

    {% csrf_token %}

    <table>
    {% for field in login_form %}
        <tr>
            <td>
                {{ field.label_tag }}
            </td>
            <td>
                {{ field }}
            </td>
            <td>
                {% if field.errors %}
                    {{ field.errors|striptags }}
                {% endif %}
            </td>
        </tr>
    {% endfor %}
    </table>
    {% if next %}
    <input type="hidden" name="next" value="{{ next }}" />
    {% endif %}
    <input type="submit" value="Log in"/>

</form>

Haven't joined N2? <strong><a href="{% url 'n2:register' %}">Register now.</a></strong>

{% endblock %}

templates/DELETE/register.html
{% extends "base.html" %}

{% block page_name %}{% spaceless %}
Register
{% endspaceless %}{% endblock %}

{% block content %}

{% if error_msg %}
    [{{ error_msg }}]
{% endif %}
{% if form_errors %}
    {{ form_errors }}
{% endif %}

<form action="{% url 'n2:register' %}" method="post">

    {% csrf_token %}

{#    <table> {{ register_form.as_table }} </table>#}

    <table>
    {% for field in register_form %}
        <tr>
            <td>
                {{ field.label_tag }}
            </td>
            <td>
                {{ field }}
            </td>
            <td>
                {% if field.errors %}
                    {{ field.errors|striptags }}
                {% endif %}
            </td>
        </tr>
    {% endfor %}
    </table>

    <input type="hidden" name="next" value="{% if next %}{{ next }}{% endif %}" />

    <input type="submit" value="Register"/>

</form>

{% endblock %}

templates/DELETE/reset_password.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block page_name %}{% spaceless %}
Reset Password
{% endspaceless %}{% endblock %}

{% block content %}
    <title></title>
</head>
{% if error_msg %}
    [{{ error_msg }}]
{% endif %}
<form action="{% url 'n2:reset' %}" method="post">

    {% csrf_token %}

    <table>
    {% for field in form %}
        <tr>
            <td>
                {{ field.label_tag }}
            </td>
            <td>
                {{ field }}
            </td>
            <td>
                {% if field.errors %}
                    {{ field.errors|striptags }}
                {% endif %}
            </td>
        </tr>
    {% endfor %}
    </table>

    <input type="hidden" name="next" value="{% if next %}{{ next }}{% endif %}" />

    <input type="submit" value="Reset password"/>

</form>
{% endblock %}

templates/DELETE/upload.html
{#<!DOCTYPE html>#}
{#<html>#}
{#<head>#}
{#    <title></title>#}
{#</head>#}
{#<body>#}
{#    <form action="{url media}" method="POST" enctype="multipart/form-data">#}
{#        {% csrf_token %}#}
{#        <p>{{ upload_form.non_field_errors }}</p>#}
{#        <p>{{ upload_form.docfile.label_tag }}</p>#}
{#        <p>#}
{#            {{ upload_form.docfile.errors }}#}
{#            {{ upload_form.docfile }}#}
{#        </p>#}
{#        <p><input type="submit" value="upload"></p>#}
{#    </form>#}
{#</body>#}
{#</html>#}

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>Upload image Form</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  </head>
  <body>
    <h1>Upload image</h1>
        {% if form.errors %}
            <p style="color: red;">
                Please correct the error{{ form.errors|pluralize }} below.
            </p>
        {% endif %}
 
        <!--malcala: please observe the enctype property below in the form header -->
        <form enctype="multipart/form-data" action="" method="post">

            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input type="submit" value="Upload image">
        </form>
  </body>
</html>