n2/urls.py
from django.conf.urls import patterns, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from n2 import views
from n2project import settings

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^login$', views.vlogin, name='login'),
    url(r'^logout$', views.vlogout, name='logout'),
    url(r'^register$', views.vregister, name='register'),
    url(r'^activate/(?P<user_pk>\d+)/(?P<activation_key>\w+)', views.activate_user, name='activate'),
    url(r'^notice/(?P<notice_id>\d+)$', views.notice, name='notice'),
    url(r'^compose$', views.compose, name='compose_new'),
    url(r'^compose/(?P<notice_id>\d+)$', views.compose, name='compose_edit'),
    url(r'^profile$', views.edit_user, name='edit_user'),
    url(r'^reset$', views.reset_password, name='reset'),
    url(r'^about$', views.about, name='about'),
    url(r'^register_complete$', views.register_complete, name='register_complete'),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

urlpatterns += staticfiles_urlpatterns()

n2project/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

# Moderator and Admin
from n2.moderator_site import moderator_site

# Dajaxice (1/2)
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
dajaxice_autodiscover()
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('',
    url(r'^admin/', include(moderator_site.urls)),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
    url(r'', include('n2.urls', namespace='n2')),
)

# Dajaxice (2/2)
urlpatterns += staticfiles_urlpatterns()

handler403 = 'n2.views.page403'
handler404 = 'n2.views.page404'
handler500 = 'n2.views.page500'

n2/forms.py
from datetime import datetime
from django import forms
from n2.models import Tag, TagGroup
from django.forms import extras
from n2project import settings

error_messages = {'required': 'Required',
                  'max_length': 'Too long',
                  'min_length': 'Too short',
                  'invalid': 'Invalid',
                  'invalid_choice': 'Invalid choice',
                  'invalid_list': 'Invalid list',
                  'missing': 'File is missing',
                  'empty': 'File is empty',
                  'invalid_image': 'Invalid image',
                  'max_value': 'Too big',
                  'min_value': 'Too small',
}

boolean_field_err_msg = {'required': 'Required',}

class login_form(forms.Form):
    username = forms.CharField(label="username", error_messages=error_messages)
    password = forms.CharField(widget=forms.PasswordInput, label="password", error_messages=error_messages)
    next = forms.CharField(widget=forms.HiddenInput, label="", error_messages=error_messages, required=False)

class register_form(forms.Form):
    username = forms.CharField(label="username", error_messages=error_messages)
    password = forms.CharField(widget=forms.PasswordInput, label="password", error_messages=error_messages)
    first_name = forms.CharField(label="first name", error_messages=error_messages)
    last_name = forms.CharField(label="last name", error_messages=error_messages)
    email = forms.EmailField(label="email", error_messages=error_messages)

def get_tags():
    all_tags = Tag.objects.filter(status='a')
    tag_choices = []
    for tag in all_tags:
        tag_choices.append((tag.pk, str(tag.tagGroup) + " - " + str(tag.tagName)))
    return tuple(tag_choices)

def get_all_tags():
    all_tags = []
    tag_groups = TagGroup.objects.all()
    for tag_group in tag_groups:
        tags = []
        for tag in tag_group.tag_set.filter(status='a'):
            tags.append({'pk': tag.pk, 'name': tag.tagName})
        all_tags.append({'group_name': tag_group.tagGroupName, 'tags': tags})
    return all_tags

class compose_form(forms.Form):
    title = forms.CharField(label="title", error_messages=error_messages)
    content = forms.CharField(label="content", widget=forms.Textarea, error_messages=error_messages)
    date_published = forms.DateField(label="date published", widget=extras.SelectDateWidget(), error_messages=error_messages)
    date_expired = forms.DateField(label="date expired", widget=extras.SelectDateWidget(), error_messages=error_messages)
    tags = forms.MultipleChoiceField(label="tags", widget=forms.CheckboxSelectMultiple, choices=get_tags(), required=False, error_messages=error_messages)
    image = forms.ImageField(label="image", required=False, error_messages=error_messages)
    original = forms.IntegerField(label="original", widget=forms.HiddenInput, initial=settings.NULL_PK, error_messages=error_messages)

def get_tag_groups():
    return [(tag_group.pk,tag_group.tagGroupName) for tag_group in TagGroup.objects.all()]
    
class add_tag_form(forms.Form):
    tag_name = forms.CharField(label='tag name', required=False, error_messages=error_messages)
    tag_group = forms.ChoiceField(label='tag group', choices=get_tag_groups(), required=False, error_messages=error_messages)
    
    def __init__(self, *args, **kwargs):
        super(add_tag_form, self).__init__(*args, **kwargs)
        self.fields['tag_name'].widget = forms.TextInput(attrs={'class':'tag_name_box'})
        self.fields['tag_group'].widget = forms.Select(attrs={'class':'tag_group_choice'})
        self.fields['tag_group'].choices = get_tag_groups()
        self.label_suffix = ''
    
    def as_table(self):
        from lxml import etree
        
        default = super(add_tag_form, self).as_table()
        added_root = '<root>'+default+'</root>'
        root = etree.fromstring(added_root)
        
        # Finds all input textfield tags
        inputs = []
        labels = []
        for i in root.iterdescendants():
            if i.tag == 'input' and 'type' in i.attrib and i.attrib['type'] == 'text':
                inputs.append(i)
            elif i.tag == 'label' and 'for' in i.attrib:
                labels.append(i)
        
        # Surround the found textfield input tags with the span tag
        for i in inputs:
            span = etree.Element('span')
            span.attrib['class'] = 'span_input_text span_input_text_create_tag'
            parent = i.getparent()
            parent.remove(i)
            parent.insert(0,span)
            span.insert(0,i)
        for l in labels:
            l.getparent().attrib['class'] = 'td_create_tag_label'
        
        # Return the modified tree back as string
        modified = ""
        for i in root:
            modified += etree.tostring(i, pretty_print=False)
        
        return modified

from django.forms.formsets import formset_factory
add_tag_formset = formset_factory(add_tag_form, extra=1)

class notice_search_form(forms.Form):
    keywords = forms.CharField(label="keywords", required=False, error_messages=error_messages)
    tags = forms.MultipleChoiceField(label="tags", widget=forms.CheckboxSelectMultiple, choices=get_tags(), required=False, error_messages=error_messages)
    show_hidden = forms.BooleanField(label="show_hidden", required=False, error_messages=error_messages)
    show_expired = forms.BooleanField(label="show_expired", required=False, error_messages=error_messages)
    bookmarked_only = forms.BooleanField(label="bookmarked_only", required=False, error_messages=error_messages)
    sort_choices = ( ('date_published', 'Recently published'),
                     ('num_views', 'Highest views'),
                     ('num_likes', 'Most liked'),
                   )
    sort_choice_default = 'date_published'
    sort_by = forms.ChoiceField(label="sort_by", widget=forms.RadioSelect, choices=sort_choices, initial=sort_choice_default, required=False, error_messages=error_messages)

    def __init__(self, *args, **kwargs):
        super(notice_search_form, self).__init__(*args, **kwargs)
        self.fields['tags'].choices = get_tags()
    
    
class user_form(forms.Form):
    username = forms.CharField(label="username", error_messages=error_messages)
    password = forms.CharField(widget=forms.PasswordInput, label="password", required=False, error_messages=error_messages)
    first_name = forms.CharField(label="first name", error_messages=error_messages)
    last_name = forms.CharField(label="last name", error_messages=error_messages)
    email = forms.EmailField(label="email", error_messages=error_messages)
    tags = forms.MultipleChoiceField(label="tags", widget=forms.CheckboxSelectMultiple, choices=get_tags(), required=False, error_messages=error_messages)

class file_form(forms.Form):
    uploaded = forms.ImageField(label='uploaded', error_messages=error_messages)

class admin_notice_form(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):
        super(admin_notice_form, self).__init__(*args, **kwargs)
        self.fields['content'].widget = forms.Textarea(attrs={'class':'vTextarea', 'cols':'50'})

class reset_password_form(forms.Form):
    username = forms.CharField(label="username", error_messages=error_messages)
    email = forms.EmailField(label="email", error_messages=error_messages)

templates/n2edit_user.html
{% extends "n2base.html" %}

{% load staticfiles %}

{% block head_title %}
    Profile
{% endblock %}

{% block head_extra %}
    <link rel="stylesheet" type="text/css" href="/media/ui/login.css">
    <style type="text/css">

            .div_content_stage
            {
                padding-bottom: 40px;
            }
            .div_content_stage_top
            {
                text-align: right;
            }
                #submit_profile
                {
                    padding: 2px 20px;
                }

            .div_content_stage_left
            {
                display: inline-block;
                width: 55%;
                vertical-align: top;
            }
                #div_centerstage_form
                {
                    margin-top: 0px;
                    margin-left: 5%;
                }
                .input_text
                {
                    height: 19px;
                }

            .div_content_stage_right
            {
                display: inline-block;
                width: 40%;
                vertical-align: top;
            }

            .div_content_stage_heading
            {
                margin-bottom: 10px;
            }
            .span_content_stage_heading
            {
                font-size: 16pt;
                color: #0090f0;
            }

            .div_content_stage_tags
            {
                margin-left: 5%;
            }
            .div_content_stage_taggroup
            {
                margin-top: 5px;
            }
            .span_content_stage_taggroup
            {
                font-weight: bold;
            }
            .div_content_stage_taggroup > label
            {
                font-size: 9pt;
            }

        </style>

{% endblock %}

{% block content %}

        <div class="div_bar_top">
            <div class="div_bar_container width_std">
                <a href="{% url 'n2:index' %}">
                    <div class="div_bar_logo">
                        <img class="img_bar_logo" src="/media/ui/n2_filterbar.png"/>
                    </div>
                </a>
                <div class="div_topping">
                    <a href="{% url 'n2:compose_new' %}">
                        <button class="n2_button_w button_create_notice_topbar">create notice</button>
                    </a>
                    <div class="div_user_dropdown">
                        <div class="div_user_dropdown_line">
                            <div class="div_user_dropdown_identifier">
                                {{ user }}
                            </div>
                            <div class="div_user_dropdown_icon">
                                <img class="img_user_dropdown_icon" src="/media/ui/dropdown.png"/>
                            </div>
                        </div>
                        <div class="div_user_dropdown_item">
                            <a href="{% url 'n2:edit_user' %}">
                                profile settings
                            </a>
                        </div>
                        <div class="div_user_dropdown_item">
                            <a href="{% url 'n2:logout' %}">
                                log out
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="div_bar_top_spacer">
        </div>

        <div class="div_page_title width_std">
            <h1 class="h1_page_title">
                profile
            </h1>
        </div>

        <form action="{% url 'n2:edit_user' %}" method="post">

            {% csrf_token %}

            <div class="div_content_stage width_std">
                <div class="div_content_stage_top">
                    <input class="n2_button" id="submit_profile" type="submit" value="save changes"/>
                </div>
                <div class="div_content_stage_left">
                    <div class="div_content_stage_heading">
                        <span class="span_content_stage_heading">
                            account details
                        </span>
                    </div>
                    <div id="div_centerstage_form">
                        <form action="{% url 'n2:register' %}" method="post">
                            <table id="table_login">
                                <tr>
                                    <td class="td_form_label{% if user_form.username.errors %} td_form_label_error{% endif %}">
                                        username
                                    </td>
                                    <td class="td_form_input">
                                       {{ user_form.username }}
                                    </td>
                                </tr>
                                <tr>
                                    <td class="td_form_label{% if user_form.password.errors %} td_form_label_error{% endif %}">
                                        password
                                    </td>
                                    <td class="td_form_input">
                                        {{ user_form.password }}
                                    </td>
                                </tr>
                                <tr>
                                    <td class="td_form_label{% if user_form.first_name.errors %} td_form_label_error{% endif %}">
                                        first name
                                    </td>
                                    <td class="td_form_input">
                                        {{ user_form.first_name }}
                                    </td>
                                </tr>
                                <tr>
                                    <td class="td_form_label{% if user_form.last_name.errors %} td_form_label_error{% endif %}">
                                        last name
                                    </td>
                                    <td class="td_form_input">
                                        {{ user_form.last_name }}
                                    </td>
                                </tr>
                                <tr>
                                    <td class="td_form_label{% if user_form.email.errors %} td_form_label_error{% endif %}">
                                        email
                                    </td>
                                    <td class="td_form_input">
                                        {{ user_form.email }}
                                    </td>
                                </tr>
                            </table>
                        </form>
                    </div>
                </div>
                <div class="div_content_stage_right">
                    <div class="div_content_stage_heading">
                        <span class="span_content_stage_heading">
                            preferred tags
                        </span>
                    </div>
                    <div class="div_content_stage_subheading">
                        {% if user_form.tags.errors %}
                            {{ user_form.tags.errors|striptags }}
                        {% endif %}
                    </div>
                    <div class="div_content_stage_tags">
                         {% for tag_group in all_tags %}
                            {% if tag_group.tags %}
                                <div class="div_content_stage_taggroup">
                                    <span class="span_content_stage_taggroup">
                                        {{ tag_group.group_name }}
                                    </span><br/>
                                    {% for tag in tag_group.tags %}
                                        <label for="id_tags_{{ tag.pk }}"><input class="input_filter_bar_tag" id="id_tags_{{ tag.pk }}" name="tags" type="checkbox" value="{{ tag.pk }}" {% if tag.pk in preferred_tags %}checked="checked"{% endif %}/>{{ tag.name }}</label><br/>
                                    {% endfor %}
                                </div>
                             {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </form>

        <div class="div_footer">
            <a href="{% url 'n2:index' %}">home</a>
            |
            <a href="{% url 'n2:about' %}">about</a>
            |
            <a href="http://www.unimelb.edu.au">unimelb</a>
        </div>

{% endblock %}

templates/n2index.html
{% extends "n2base.html" %}

{% block head_title %}
    N2
{% endblock %}

{% block head_extra %}
        <script src="/media/ui/jquery.js"></script>
        <script src="/media/ui/benholland_positioning.js"></script>
        <style type="text/css">

            .div_topping
            {
                position: absolute;
                right: 20px;
                top: 10px;
                min-width: 300px;
                text-align: right;
                left: 237px;
            }
                .div_user_dropdown
                {
                    box-shadow: 0px 3px 10px rgba(0,0,0,0.2);
                }

            #div_filter_bar
            {
                background: #00b0f0; /* Old browsers */
                background: -moz-linear-gradient(top,  #00b0f0 0%, #0070c0 50%); /* FF3.6+ */
                background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#00b0f0), color-stop(50%,#0070c0)); /* Chrome,Safari4+ */
                background: -webkit-linear-gradient(top,  #00b0f0 0%,#0070c0 50%); /* Chrome10+,Safari5.1+ */
                background: -o-linear-gradient(top,  #00b0f0 0%,#0070c0 50%); /* Opera 11.10+ */
                background: -ms-linear-gradient(top,  #00b0f0 0%,#0070c0 50%); /* IE10+ */
                background: linear-gradient(to bottom,  #00b0f0 0%,#0070c0 50%); /* W3C */
                filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#00b0f0', endColorstr='#0070c0',GradientType=0 ); /* IE6-9 */
                background-color: #2fbcef;
                min-height: 100%;
                width: 220px;
                float: left;
                text-align: center;
                color: #fff;
                box-shadow: 0px 0px 20px rgba(0,0,0,0.5);
                font-size: 9pt;
                line-height: 3pt;
            }



            #div_filter_bar_logo
            {
                width: 50%;
                height: 73px;
                margin-top: 20px;
                margin-bottom: 20px;
                margin-left: auto;
                margin-right: auto;
            }
            #img_filter_bar_logo
            {
                max-width: 100%;
            }
            #div_filter_bar_sep
            {
                border-top: solid 1px #fff;
                margin-top: 15px;
                width: 80%;
                margin-left: auto;
                margin-right: auto;
            }
            #submit_filter
            {
                margin-top: 20px;
                padding: 2px 50px;
            }
            .div_filter_bar_heading
            {
                margin-top: 17px;
                margin-bottom: 3px;
            }
            .span_filter_bar_heading
            {
                font-size: 8pt;
                letter-spacing: 2pt;
            }
            #id_keywords
            {
                margin-top: 3px;
            }
            .div_filter_bar_group
            {
                text-align: left;
                margin-left: 10px;
                margin-right: 10px;
            }
            .div_filter_bar_tag_heading
            {
                margin-top: 10px;
                margin-bottom: 5px;
            }
            .span_filter_bar_tag_heading
            {
                font-weight: bold;
                font-size: 9pt;
            }

            .div_notice_card
            {
                position: absolute;
                background-color: #fff;
                width: 200px;
                padding: 8px;
                cursor: pointer;
                -webkit-transition: all 0.3s ease-in-out;
                -moz-transition: all 0.3s ease-in-out;
                -o-transition: all 0.3s ease-in-out;
                -ms-transition: all 0.3s ease-in-out;
                transition: all 0.3s ease-in-out;
                top: 1500px;
                left: 600px;
                box-shadow: 0px 5px 10px rgba(0, 0, 0, 0.25);
            }
            .div_notice_card:hover
            {
                box-shadow: 0px 5px 10px rgba(0, 119, 240, 0.35);
            }
            .div_notice_card_image
            {
                max-height: 200px;
                text-align: center;
            }
            .img_notice_card_img
            {
                max-width: 100%;
                max-height: 200px;
            }
            .div_notice_card_title
            {
                margin-top: 5px;
                overflow: hidden;
            }
            .span_notice_card_title
            {
                font-size: 14pt;
                font-weight: bold;
                color: black;
            }
            .div_notice_card_snippet
            {
                overflow: hidden;
            }
            .span_notice_card_snippet
            {
                font-size: 9pt;
                color: black;
            }
            .div_notice_card_properties
            {
                overflow: hidden;
            }
            .span_notice_card_properties
            {
                font-size: 8pt;
                color: #979797;
            }
            .div_notice_card_counts
            {
                margin-top: 5px;
            }
            .span_notice_card_count_value
            {
                font-weight: bold;
                color: #0074fa;
            }
            .span_notice_card_count_unit
            {
                color: #0074fa;
            }

            .div_footer_bar
            {
                margin-top: 50px;
            }

            .div_dashboard_message
            {
                position: absolute;
                top: 180px;
                left: 300px;
            }
            .span_dashboard_message
            {
                font-size: 36pt;
                color: rgb(213, 213, 213);
                position: relative;
                padding: 91px;
                letter-spacing: -2pt;
                text-shadow: -1px -1px 1px rgb(184, 184, 184);
            }
            .span_dashboard_message:before
            {
                content: attr(title);
                color: rgba(255, 255, 255, 1);
                position: absolute;
                padding: 90px;
                letter-spacing: -2pt;
            }
            .span_dashboard_message:before
            {
                top: 1px;
                left: 1px;
                opacity: 0.4;
            }


        </style>
{% endblock %}

{% block body_onload_extension %}
    setupBlocks();
{% endblock %}

{% block content %}

        <div class="div_topping">
            <a href="{% url 'n2:compose_new' %}">
                <button class="n2_button" id="button_create_notice">create notice</button>
            </a>
            <div class="div_user_dropdown">
                <div class="div_user_dropdown_line">
                    <div class="div_user_dropdown_identifier">
                        {{ user }}
                    </div>
                    <div class="div_user_dropdown_icon">
                        <img class="img_user_dropdown_icon" src="/media/ui/dropdown.png"/>
                    </div>
                </div>
                <div class="div_user_dropdown_item">
                    <a href="{% url 'n2:edit_user' %}">
                        profile settings
                    </a>
                </div>
                <div class="div_user_dropdown_item">
                    <a href="{% url 'n2:logout' %}">
                        log out
                    </a>
                </div>
            </div>
        </div>

        <div id="div_filter_bar">

            <a href="{% url 'n2:index' %}">
                <div id="div_filter_bar_logo">
                    <img id="img_filter_bar_logo" src="/media/ui/n2_filterbar.png"/>
                </div>
            </a>
            <div id="div_filter_bar_sep">
            </div>
            <form>

                <!-- Submit -->
                <input class="n2_button_w" id="submit_filter" type="submit" value="filter"/>

                <!-- Keywords -->
                <div class="div_filter_bar_heading">
                    <span class="span_filter_bar_heading">KEYWORDS</span>
                </div>
                <span class="span_input_text">
                    {{ notice_search_form.keywords }}
                </span>

                <!-- Options -->
                <div class="div_filter_bar_heading">
                    <span class="span_filter_bar_heading">OPTIONS</span>
                </div>
                <div class="div_filter_bar_group">
                    <label for="id_bookmarked_only">{{ notice_search_form.bookmarked_only }}Bookmarked only</label><br/>
                    <label for="id_show_hidden">{{ notice_search_form.show_hidden }}Show hidden</label><br/>
                    <label for="id_show_expired">{{ notice_search_form.show_expired }}Show expired</label><br/>
                </div>

                <!-- Sort -->
                <div class="div_filter_bar_heading">
                    <span class="span_filter_bar_heading">SORT BY</span>
                </div>
                <div class="div_filter_bar_group">
                    {% for radio in notice_search_form.sort_by %}
                        <label>
                            {{ radio.tag }}
                            {{ radio.choice_label }}
                        </label>
                        <br/>
                    {% endfor %}
                </div>

                <!-- Tags -->
                <div class="div_filter_bar_heading">
                    <span class="span_filter_bar_heading">TAGS</span>
                </div>
                {% for tag_group in all_tags %}
                    {% if tag_group.tags %}
                        <div class="div_filter_bar_group">
                            <div class="div_filter_bar_tag_heading">
                                <span class="span_filter_bar_tag_heading">{{ tag_group.group_name }}</span><br/>
                            </div>
                            {% for tag in tag_group.tags %}
                                <label for="id_tags_{{ tag.pk }}"><input class="input_filter_bar_tag" id="id_tags_{{ tag.pk }}" name="tags" type="checkbox" value="{{ tag.pk }}" {% if tag.pk in selected_tags %}checked="checked"{% endif %}/>{{ tag.name }}</label><br/>
                            {% endfor %}
                            <br/>
                        </div>
                    {% endif %}
                {% endfor %}

                <!-- Footer -->
                <div class="div_footer_bar">
                    <a href="{% url 'n2:about' %}">about</a>
                    |
                    <a href="http://www.unimelb.edu.au">unimelb</a>
                </div>
            </form>
        </div>

        <div id="div_dashboard_content">

            {% if notices %}
                {% for notice in notices %}
                    <a href="{% url 'n2:notice' notice.pk %}">
                        <div class="div_notice_card">
                            {% if notice.image %}
                                <div class="div_notice_card_image">
                                    <img class="img_notice_card_img" src="{{ notice.image.url }}"/>
                                </div>
                            {% endif %}
                            <div class="div_notice_card_title">
                                <span class="span_notice_card_title">{{ notice.title|striptags }}</span>
                            </div>
                            <div class="div_notice_card_snippet">
                                <span class="span_notice_card_snippet"> {{ notice.content|truncatewords:25|striptags }}</span>
                            </div>
                            <div class="div_notice_card_properties">
                                <span class="span_notice_card_properties">by {{ notice.author }} on {{ notice.datePublished|date:"j M Y" }}</span>
                            </div>
                            <div class="div_notice_card_counts">
                                <span class="span_notice_card_count_value">{{ notice.num_views }}</span> <span class="span_notice_card_count_unit">views</span>,
                                <span class="span_notice_card_count_value">{{ notice.num_likes }}</span> <span class="span_notice_card_count_unit">likes</span>
                            </div>
                        </div>
                    </a>
                {% endfor %}
            {% else %}
                <div class="div_dashboard_message">
                    <span class="span_dashboard_message" title="No results.">
                        No results.
                    </span>
                </div>
            {% endif %}

        </div>

{% endblock %}